#!/bin/bash

echo "Enter the name: "
read name

whitespace='                          '
recurse(){
  if [[ $name =~ [A-Z] && $name =~ ^[[:upper:]]+$ ]]
  then
    name=$(echo $name | tr [:upper:] [:lower:])
    elif [[ $name =~ [a-z] ]]
  then

echo "Enter the name in Upper Case: "
read name

recurse
fi
}
recurse
name1=$name
for((i=${#name1};i>1;i-=1))
  do
  if [[ $i == ${#name1} ]]
  then
    name2="${name1:i-1:1}"
  echo "${whitespace:0:i-1}""$name2"
  else
    name2="${name1:i-1:(${#name1}+1)}"
  for((b=${#name2};b>1;b-=1))
  do
    name3="${name2:b-2:1}"
    name4=$name4$name3
done
  echo "${whitespace:0:i-1}""$name2""$name4"
  fi
    name4=""
done
a=0
for((i=${#name};i>0;i-=1))
do
    name3=""
  if [[ $i == ${#name} ]]
  then
    name1="${name:0:i}"
for((j=${#name1};j>1;j-=1))
do
    name2="${name1:j-2:1}"
    name3=$name3$name2
done
else
    name1="${name:1:(${#name}-2)}"
fi
echo "${whitespace:0:$a}""$name1""$name3"
    name=$name1$name3
    a=$a+1
done


      
Enter the name :
deshashri
Enter the name in Upper Case:
DESHASHRI
        i
       rir
      hrirh
     shrirhs
    ashrirhsa
   hashrirhsah
  shashrirhsahs
 eshashrirhsahse
deshashrirhsahsed
 eshashrirhsahse
  shashrirhsahs
   hashrirhsah
    ashrirhsa
     shrirhs
      hrirh
       rir
        i
