#!/bin/bash
echo "Enter name:"
read name
whitespace='              '
if [[ $name =~ [A-Z] ]]
then
    name=$(echo $name | tr [:upper:] [:lower:])
fi
a=0
for((p=${#name};p>0;p-=1))
do
    name3=""
if [[ $p == ${#name} ]]
then
    name1="${name:0:p}"
for((q=${#name1};q>1;q-=1))
do
    name2="${name1:q-2:1}"
    name3=$name3$name2
done
else
    name1="${name:1:(${#name}-2)}"
fi
echo "${whitespace:0:$a}""$name1""$name3"
    name=$name1$name3
    a=$a+1
done

Output:

Enter name:
Deshashri
deshashrirhsahsed
 eshashrirhsahse
  shashrirhsahs
   hashrirhsah
    ashrirhsa
     shrirhs
      hrirh
       rir
        i
