#!/bin/bash

       #Installing docker
       echo "**INSTALLING DOCKER**"
       sudo dnf -y install docker
       sudo dnf upgrade --releasever=2023.1.20230705
       sudo systemctl start docker
       sudo docker run hello-world


        #Installing Minikube
        echo "**INSTALLING MINIKUBE**"
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        sudo minikube version
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm64
        sudo install minikube-linux-arm64 /usr/local/bin/minikube

        sudo docker --version
        echo minikube and docker was successfully installed
        echo manually run minikube start --vm-driver=docker --cni=calico to start minikube
        sudo usermod -aG docker $USER
        newgrp docker
